/**
 * Lock-in parameter indices extracted from main.h
 */
#ifndef __LOCK_PARAMS_H
#define __LOCK_PARAMS_H

#define LOCK_OSCA_SW                    81
#define LOCK_OSCB_SW                    82
#define LOCK_OSC1_FILT_OFF              83
#define LOCK_OSC2_FILT_OFF              84
#define LOCK_OSC_RAW_MODE               85
#define LOCK_OSC_LOCKIN_MODE            86
#define LOCK_TRIG_SW                    87
#define LOCK_OUT1_SW                    88
#define LOCK_OUT2_SW                    89
#define LOCK_SLOW_OUT1_SW               90
#define LOCK_SLOW_OUT2_SW               91
#define LOCK_SLOW_OUT3_SW               92
#define LOCK_SLOW_OUT4_SW               93
#define LOCK_LOCK_CONTROL               94
#define LOCK_LOCK_FEEDBACK              95
#define LOCK_LOCK_TRIG_VAL              96
#define LOCK_LOCK_TRIG_TIME_VAL         97
#define LOCK_LOCK_TRIG_SW               98
#define LOCK_RL_ERROR_THRESHOLD         99
#define LOCK_RL_SIGNAL_SW               100
#define LOCK_RL_SIGNAL_THRESHOLD        101
#define LOCK_RL_ERROR_ENABLE            102
#define LOCK_RL_SIGNAL_ENABLE           103
#define LOCK_RL_RESET                   104
#define LOCK_RL_STATE                   105
#define LOCK_SF_JUMPA                   106
#define LOCK_SF_JUMPB                   107
#define LOCK_SF_START                   108
#define LOCK_SF_AFRZO                   109
#define LOCK_SF_AFRZI                   110
#define LOCK_SF_BFRZO                   111
#define LOCK_SF_BFRZI                   112
#define LOCK_SIGNAL_SW                  113
#define LOCK_SIGNAL_I                   114
#define LOCK_SG_AMP1                    115
#define LOCK_SG_AMP2                    116
#define LOCK_SG_AMP3                    117
#define LOCK_SG_AMP_SQ                  118
#define LOCK_LPF_F1_TAU                 119
#define LOCK_LPF_F1_ORDER               120
#define LOCK_LPF_F2_TAU                 121
#define LOCK_LPF_F2_ORDER               122
#define LOCK_LPF_F3_TAU                 123
#define LOCK_LPF_F3_ORDER               124
#define LOCK_LPF_SQ_TAU                 125
#define LOCK_LPF_SQ_ORDER               126
#define LOCK_ERROR_SW                   127
#define LOCK_ERROR_OFFSET               128
#define LOCK_ERROR                      129
#define LOCK_ERROR_MEAN                 130
#define LOCK_ERROR_STD                  131
#define LOCK_GEN_MOD_PHASE              132
#define LOCK_GEN_MOD_PHASE_SQ           133
#define LOCK_GEN_MOD_HP                 134
#define LOCK_GEN_MOD_SQP                135
#define LOCK_RAMP_A                     136
#define LOCK_RAMP_B                     137
#define LOCK_RAMP_STEP                  138
#define LOCK_RAMP_LOW_LIM               139
#define LOCK_RAMP_HIG_LIM               140
#define LOCK_RAMP_RESET                 141
#define LOCK_RAMP_ENABLE                142
#define LOCK_RAMP_DIRECTION             143
#define LOCK_RAMP_B_FACTOR              144
#define LOCK_SIN_REF                    145
#define LOCK_COS_REF                    146
#define LOCK_COS_1F                     147
#define LOCK_COS_2F                     148
#define LOCK_COS_3F                     149
#define LOCK_SQ_REF_B                   150
#define LOCK_SQ_QUAD_B                  151
#define LOCK_SQ_PHAS_B                  152
#define LOCK_SQ_REF                     153
#define LOCK_SQ_QUAD                    154
#define LOCK_SQ_PHAS                    155
#define LOCK_IN1                        156
#define LOCK_IN2                        157
#define LOCK_OUT1                       158
#define LOCK_OUT2                       159
#define LOCK_SLOW_OUT1                  160
#define LOCK_SLOW_OUT2                  161
#define LOCK_SLOW_OUT3                  162
#define LOCK_SLOW_OUT4                  163
#define LOCK_OSCA                       164
#define LOCK_OSCB                       165
#define LOCK_X_28                       166
#define LOCK_Y_28                       167
#define LOCK_F1_28                      168
#define LOCK_F2_28                      169
#define LOCK_F3_28                      170
#define LOCK_SQX_28                     171
#define LOCK_SQY_28                     172
#define LOCK_SQF_28                     173
#define LOCK_CNT_CLK                    174
#define LOCK_CNT_CLK2                   175
#define LOCK_READ_CTRL                  176
#define LOCK_PIDA_SW                    177
#define LOCK_PIDA_PSR                   178
#define LOCK_PIDA_ISR                   179
#define LOCK_PIDA_DSR                   180
#define LOCK_PIDA_SAT                   181
#define LOCK_PIDA_SP                    182
#define LOCK_PIDA_KP                    183
#define LOCK_PIDA_KI                    184
#define LOCK_PIDA_KD                    185
#define LOCK_PIDA_IN                    186
#define LOCK_PIDA_OUT                   187
#define LOCK_PIDA_IRST                  188
#define LOCK_PIDA_FREEZE                189
#define LOCK_PIDA_IFREEZE               190
#define LOCK_CTRL_A                     191
#define LOCK_PIDB_SW                    192
#define LOCK_PIDB_PSR                   193
#define LOCK_PIDB_ISR                   194
#define LOCK_PIDB_DSR                   195
#define LOCK_PIDB_SAT                   196
#define LOCK_PIDB_SP                    197
#define LOCK_PIDB_KP                    198
#define LOCK_PIDB_KI                    199
#define LOCK_PIDB_KD                    200
#define LOCK_PIDB_IN                    201
#define LOCK_PIDB_OUT                   202
#define LOCK_PIDB_IRST                  203
#define LOCK_PIDB_FREEZE                204
#define LOCK_PIDB_IFREEZE               205
#define LOCK_CTRL_B                     206
#define LOCK_AUX_A                      207
#define LOCK_AUX_B                      208
#define LOCK_CTRL_AUX_LOCK_NOW          209
#define LOCK_CTRL_AUX_LAUNCH_LOCK_TRIG  210
#define LOCK_CTRL_AUX_PIDB_ENABLE_CTRL  211
#define LOCK_CTRL_AUX_PIDA_ENABLE_CTRL  212
#define LOCK_CTRL_AUX_RAMP_ENABLE_CTRL  213
#define LOCK_CTRL_AUX_SET_PIDB_ENABLE   214
#define LOCK_CTRL_AUX_SET_PIDA_ENABLE   215
#define LOCK_CTRL_AUX_SET_RAMP_ENABLE   216
#define LOCK_CTRL_AUX_TRIG_TYPE         217
#define LOCK_CTRL_AUX_LOCK_TRIG_RISE    218
#define LOCK_MOD_SQ_ON                  219
#define LOCK_MOD_HARMONIC_ON            220

#endif /* __LOCK_PARAMS_H */
